DPCM_GUITAR_START = $00
DPCM_SFX_START = $50
DPCM_LINES_START = $60

.enum 0
; BANK 1
DMC_START_WCPGW:	.dsb $ff
DMC_START_WCPGW_END:
	.dsb 1
DMC_START_DIMIDLH:	.dsb $ff
DMC_START_DIMIDLH_END:
	.dsb 1
; BANK 2
DMC_START_MLABTS:	.dsb $ff
DMC_START_MLABTS_END:
	.dsb 1
DMC_START_HWBYHB:	.dsb $ff
DMC_START_HWBYHB_END:
	.dsb 1
; BANK 3
DMC_START_HITISEBT:	.dsb $ff
DMC_START_HITISEBT_END:
	.dsb 1
DMC_START_STBFUO:	.dsb $ff
DMC_START_STBFUO_END:
	.dsb 1
; BANK 4
DMC_START_WIWFC:	.dsb $ff
DMC_START_WIWFC_END:
	.dsb 1
DMC_START_GAMMD:	.dsb $ff
DMC_START_GAMMD_END:
	.dsb 1
; BANK 5
DMC_START_MCDNMP:	.dsb $ff
DMC_START_MCDNMP_END:
	.dsb 1
DMC_START_HIDWTS:	.dsb $ff
DMC_START_HIDWTS_END:
	.dsb 1
; BANK 6
DMC_START_NTIGASC:	.dsb $ff
DMC_START_NTIGASC_END:
	.dsb 1
DMC_START_ITAVITA:	.dsb $ff
DMC_START_ITAVITA_END:
	.dsb 1
; BANK 7
DMC_START_TIIOHYCMM:	.dsb $ff
DMC_START_TIIOHYCMM_END:
	.dsb 1
DMC_START_WAGUSB:	.dsb $ff
DMC_START_WAGUSB_END:
	.dsb 1
; BANK 8
DMC_START_SD911:	.dsb $ff
DMC_START_SD911_END:
	.dsb 1
DMC_START_WAYSPTT:	.dsb $ff
DMC_START_WAYSPTT_END:
	.dsb 1
; BANK 9
DMC_SHATTER:	.dsb $ff
DMC_SHATTER_END:
	.dsb 1
DMC_GTR_1:	.dsb $fe
DMC_GTR_1_END:
	.dsb 2
; BANK 10
DMC_GTR_2:	.dsb $fe
DMC_GTR_2_END:
	.dsb 2
DMC_GTR_3:	.dsb $fe
DMC_GTR_3_END:
	.dsb 2
; BANK 11
DMC_GTR_4:	.dsb $fe
DMC_GTR_4_END:
	.dsb 2
DMC_GTR_5:	.dsb $fe
DMC_GTR_5_END:
	.dsb 2
; BANK 12
DMC_END_STBFUO:	.dsb $fa
DMC_END_STBFUO_END:
	.dsb 2
DMC_END_WAYSPTT:	.dsb $da
DMC_END_WAYSPTT_END:
	.dsb 2
DMC_FALLING_PIANO:	.dsb $26
DMC_FALLING_PIANO_END:
	.dsb 2
; BANK 13
DMC_BOTTOMLESS_PIT_2:	.dsb $d0
DMC_BOTTOMLESS_PIT_2_END:
DMC_END_ITAVITA:	.dsb $99
DMC_END_ITAVITA_END:
	.dsb 3
DMC_END_MCDNMP:	.dsb $93
DMC_END_MCDNMP_END:
	.dsb 1
; BANK 14
DMC_SHAKE_DRY:	.dsb $c7
DMC_SHAKE_DRY_END:
	.dsb 1
DMC_BOTTOMLESS_PIT_1:	.dsb $a1
DMC_BOTTOMLESS_PIT_1_END:
	.dsb 3
DMC__YIKES_:	.dsb $51
DMC__YIKES__END:
	.dsb 3
DMC_END_WCPGW:	.dsb $40
DMC_END_WCPGW_END:
; BANK 15
DMC_EGG_BOUNCE:	.dsb $9e
DMC_EGG_BOUNCE_END:
	.dsb 2
DMC_END_GAMMD:	.dsb $88
DMC_END_GAMMD_END:
DMC_END_NTIGASC:	.dsb $77
DMC_END_NTIGASC_END:
	.dsb 1
DMC__HELLO_:	.dsb $5e
DMC__HELLO__END:
	.dsb 2
; BANK 16
DMC_END_DIMIDLH:	.dsb $84
DMC_END_DIMIDLH_END:
DMC_END_TIIOHYCMM:	.dsb $7d
DMC_END_TIIOHYCMM_END:
	.dsb 3
DMC_END_SD911:	.dsb $79
DMC_END_SD911_END:
	.dsb 3
DMC_END_MLABTS:	.dsb $5d
DMC_END_MLABTS_END:
	.dsb 3
DMC_END_HWBYHB:	.dsb $1d
DMC_END_HWBYHB_END:
	.dsb 3
; BANK 17
DMC_END_HITISEBT:	.dsb $6b
DMC_END_HITISEBT_END:
	.dsb 1
DMC__YOW_:	.dsb $4c
DMC__YOW__END:
DMC_END_HIDWTS:	.dsb $41
DMC_END_HIDWTS_END:
	.dsb 3
DMC_END_WAGUSB:	.dsb $3f
DMC_END_WAGUSB_END:
	.dsb 1
DMC_ACCORDIAN_GAG:	.dsb $2b
DMC_ACCORDIAN_GAG_END:
	.dsb 1
DMC_END_WIWFC:	.dsb $0f
DMC_END_WIWFC_END:
	.dsb 1
	.dsb $88
.ende

.enum DPCM_SFX_START & $3f
SMP_EGG_BOUNCE:		.dsb 1
SMP_ACCORDION_GAG_1:	.dsb 1
SMP_ACCORDION_GAG_2:	.dsb 1
SMP_SHAKE_DRY:		.dsb 1
SMP_FALLING_PIANO_1:	.dsb 1
SMP_FALLING_PIANO_2:	.dsb 1
SMP_FALLING_PIANO_3:	.dsb 1
SMP_FALLING_PIANO_4:	.dsb 1
SMP_FALLING_PIANO_5:	.dsb 1
SMP_SHATTER:		.dsb 1
SMP__HELLO_:		.dsb 1
SMP_BOTTOMLESS_PIT:	.dsb 2
SMP__YIKES_:		.dsb 1
SMP__YOW_:		.dsb 1
	.dsb 1
SMP_WHAT_COULD_POSSIBLY_GO_WRONG:		.dsb 2
SMP_DID_I_MENTION_I_DON_T_LIKE_HEIGHTS:		.dsb 2
SMP_MORE_LIKE_A_BRIDGE_TOO_SHORT:		.dsb 2
SMP_HEY_WHATEVER_BLOWS_YOUR_HAIR_BACK:		.dsb 2
SMP_HEY_I_THOUGHT_I_SAW_ELVIS_BACK_THERE:	.dsb 2
SMP_SHOULDN_T_THAT_BE_FEARLESS_UH_OH:		.dsb 2
SMP_WELL_IT_WORKED_FOR_CLINT:			.dsb 2
SMP_GO_AHEAD_MAKE_MY_DAY:			.dsb 2
SMP_MY_CONTRACT_DOES_NOT_MENTION_PAIN:		.dsb 2
SMP_HEY_I_DIDN_T_WRITE_THIS_STUFF:		.dsb 2
SMP_NEXT_TIME_I_GET_A_STUNT_CAT:		.dsb 2
SMP_IS_THERE_A_VETERINARIAN_IN_THE_AUDIENCE:	.dsb 2
SMP_THAT_S_IT_I_M_OUTTA_HERE_YOU_CAN_T_MAKE_ME:	.dsb 2
SMP_WHAT_AND_GIVE_UP_SHOW_BUSINESS:		.dsb 2
SMP_SOMEBODY_DIAL_911:				.dsb 2
SMP_WHOA_ARE_YOU_STILL_PLAYING_THIS_THING:	.dsb 2
.ende