SfxPointers:
;			mus/sfx	bank		label
	audio_ptr	1,	PRG_SFX0,	SFX_Splat
	audio_ptr	1,	PRG_SFX0,	SFX_Blink
	audio_ptr	1,	PRG_SFX0,	SFX_Cuckoo
	audio_ptr	1,	PRG_SFX0,	SFX_AhrrgHeightShock
	audio_ptr	1,	PRG_SFX0,	SFX_ScreenTapping
	audio_ptr	0,	PRG_SFX0,	SFX_Skid
	audio_ptr	1,	PRG_SFX0,	SFX_BananaSlide
	audio_ptr	1,	PRG_SFX0,	SFX_LowJump
	audio_ptr	1,	PRG_SFX0,	SFX_HighJump
	audio_ptr	1,	PRG_SFX0,	SFX_HitEnemyOrWall
	audio_ptr	1,	PRG_SFX0,	SFX_DazedBirdTweet
	audio_ptr	1,	PRG_SFX0,	SFX_LandedOnSharpSurface
	audio_ptr	1,	PRG_SFX0,	SFX_Yarn1
	audio_ptr	1,	PRG_SFX0,	SFX_Yarn2
	audio_ptr	1,	PRG_SFX0,	SFX_Yarn3
	audio_ptr	1,	PRG_SFX0,	SFX_Yarn4
	audio_ptr	1,	PRG_SFX0,	SFX_EggDropped
	audio_ptr	0,	PRG_SFX0,	SFX_MadCarHonk1
	audio_ptr	0,	PRG_SFX0,	SFX_MadCarHonk2
	audio_ptr	0,	PRG_SFX0,	SFX_MadCarHonk3
	audio_ptr	1,	PRG_SFX0,	SFX_SilkSaucer
	audio_ptr	1,	PRG_SFX0,	SFX_WoolieRaspberry
	audio_ptr	1,	PRG_SFX0,	SFX_Splash
	audio_ptr	0,	PRG_SFX0,	SFX_LevelSwitchManholeCover
	audio_ptr	0,	PRG_SFX0,	SFX_BridgeWheel
	audio_ptr	1,	PRG_SFX0,	SFX_DynamitePrairieDogGunshot
	audio_ptr	0,	PRG_SFX0,	SFX_CollectContinue
	audio_ptr	0,	PRG_SFX0,	SFX_YarnCrate
	audio_ptr	0,	PRG_SFX0,	SFX_YarnBubble
	audio_ptr	0,	PRG_SFX0,	SFX_1UpShirt
	audio_ptr	0,	PRG_SFX0,	SFX_2UpShirt
	audio_ptr	1,	PRG_SFX0,	SFX_FootTap
	audio_ptr	1,	PRG_SFX0,	SFX_BigBallOfViolence
	audio_ptr	1,	PRG_SFX0,	SFX_Faint
	audio_ptr	1,	PRG_SFX0,	SFX_FaintThud
	audio_ptr	0,	PRG_SFX0,	SFX_Melting
	audio_ptr	1,	PRG_SFX0,	SFX_AlarmClockOutOfTime
	audio_ptr	1,	PRG_SFX0,	SFX_SnapagatorChomp
	audio_ptr	1,	PRG_SFX0,	SFX_FlyingBug
	audio_ptr	1,	PRG_SFX0,	SFX_FirecrackerSizzle
	audio_ptr	1,	PRG_SFX0,	SFX_Bounce
	audio_ptr	1,	PRG_SFX0,	SFX_EggCrack
	audio_ptr	1,	PRG_SFX0,	SFX_BootKick
	audio_ptr	1,	PRG_SFX0,	SFX_TreeFrogCroak
	audio_ptr	0,	PRG_SFX0,	SFX_KnockoutBells
	audio_ptr	1,	PRG_SFX0,	SFX_Chapter1
	audio_ptr	1,	PRG_SFX0,	SFX_Chapter2
	audio_ptr	1,	PRG_SFX0,	SFX_Chapter3
	audio_ptr	1,	PRG_SFX0,	SFX_Chapter4
	audio_ptr	1,	PRG_SFX0,	SFX_Chapter5
	audio_ptr	1,	PRG_SFX0,	SFX_Chapter6
	audio_ptr	1,	PRG_SFX0,	SFX_Chapter7
	audio_ptr	1,	PRG_SFX0,	SFX_Chapter8
	audio_ptr	1,	PRG_SFX0,	SFX_Chapter9
	audio_ptr	1,	PRG_SFX0,	SFX_Chapter10
	audio_ptr	1,	PRG_SFX0,	SFX_Chapter11
	audio_ptr	1,	PRG_SFX0,	SFX_Chapter12
	audio_ptr	1,	PRG_SFX0,	SFX_Chapter13
	audio_ptr	1,	PRG_SFX0,	SFX_Chapter14
	audio_ptr	1,	PRG_SFX0,	SFX_Chapter15
	audio_ptr	1,	PRG_SFX0,	SFX_Chapter16
	audio_ptr	1,	PRG_SFX0,	SFX_EggBounce
	audio_ptr	1,	PRG_SFX0,	SFX_WalkingAccordionGag1
	audio_ptr	1,	PRG_SFX0,	SFX_WalkingAccordionGag2
	audio_ptr	1,	PRG_SFX0,	SFX_ShakeDry
	audio_ptr	1,	PRG_SFX0,	SFX_FallingPiano1
	audio_ptr	1,	PRG_SFX0,	SFX_FallingPiano2
	audio_ptr	1,	PRG_SFX0,	SFX_FallingPiano3
	audio_ptr	1,	PRG_SFX0,	SFX_FallingPiano4
	audio_ptr	1,	PRG_SFX0,	SFX_FallingPiano5
	audio_ptr	1,	PRG_SFX0,	SFX_Shatter
	audio_ptr	1,	PRG_SFX0,	SFX_Hello
	audio_ptr	1,	PRG_SFX0,	SFX_BottomlessPit
	audio_ptr	1,	PRG_SFX0,	SFX_Yikes
	audio_ptr	1,	PRG_SFX0,	SFX_Yow
